### ISSUE TITLE
Metadata version mismatch for module...

### ISSUE THREAD

**Issue by BabC** [sollenne/angular-fittext#23]
Hi !

Thanks for the lib, it works well =)
But I have an issue on your v2.1.1 similar to #9 for angular4

`ERROR in Metadata version mismatch for module [...]/angular-fittext/angular-fittext.d.ts, found version 4, expected 3, resolving symbol [...]`

I've downgraded to v2.0.7 and our build was succefull.
If somebody else has this issue, the downgrade to v2.0.7 is the solution ;)

**Comment by sollenne** [comment]
Thanks. I'll upgrade the dependencies today
